// Eurovision Song Contest 2026 – Grand Final Data
// Vienna, Austria · 16 May 2026
// Auto-qualifiers: Austria (host), France, Germany, Italy, UK (Big 4)
// Semi-Final 1 qualifiers (confirmed): Belgium, Croatia, Finland, Greece, Israel, Lithuania, Moldova, Poland, Serbia, Sweden
// Semi-Final 2 qualifiers (May 14 — results pending, full list included as per competition entry list)

const COUNTRIES = [
  // ── Grand Finalists (in running order) ────────────────────────
  {
    id: "denmark",
    country: "Denmark",
    flag: "🇩🇰",
    flagCode: "DK",
    artist: "Søren Torpegaard Lund",
    song: "Før vi går hjem",
    youtubeId: "SorenDenmark2026",
    youtubeSearch: "Søren Torpegaard Lund Før vi går hjem Denmark Eurovision 2026",
    qualified: "sf2",
    runningOrder: 1,
  },
  {
    id: "germany",
    country: "Germany",
    flag: "🇩🇪",
    flagCode: "DE",
    artist: "Sarah Engels",
    song: "Fire",
    youtubeId: "SarahEngelsFire2026",
    youtubeSearch: "Sarah Engels Fire Germany Eurovision 2026",
    qualified: "big5",
    runningOrder: 2,
  },
  {
    id: "israel",
    country: "Israel",
    flag: "🇮🇱",
    flagCode: "IL",
    artist: "Noam Bettan",
    song: "Michelle",
    youtubeId: "NoamBettanMichelle2026",
    youtubeSearch: "Noam Bettan Michelle Israel Eurovision 2026",
    qualified: "sf1",
    runningOrder: 3,
  },
  {
    id: "belgium",
    country: "Belgium",
    flag: "🇧🇪",
    flagCode: "BE",
    artist: "ESSYLA",
    song: "Dancing on the Ice",
    youtubeId: "ESSDancingOnIce2026",
    youtubeSearch: "ESSYLA Dancing on the Ice Belgium Eurovision 2026",
    qualified: "sf1",
    runningOrder: 4,
  },
  {
    id: "albania",
    country: "Albania",
    flag: "🇦🇱",
    flagCode: "AL",
    artist: "Alis",
    song: "Nân",
    youtubeId: "AlisNan2026",
    youtubeSearch: "Alis Nân Albania Eurovision 2026",
    qualified: "sf2",
    runningOrder: 5,
  },
  {
    id: "greece",
    country: "Greece",
    flag: "🇬🇷",
    flagCode: "GR",
    artist: "Akylas",
    song: "Ferto",
    youtubeId: "AkylasFerto2026",
    youtubeSearch: "Akylas Ferto Greece Eurovision 2026",
    qualified: "sf1",
    runningOrder: 6,
  },
  {
    id: "ukraine",
    country: "Ukraine",
    flag: "🇺🇦",
    flagCode: "UA",
    artist: "Leléka",
    song: "Ridnym",
    youtubeId: "LelekaRidnym2026",
    youtubeSearch: "Leléka Ridnym Ukraine Eurovision 2026",
    qualified: "sf2",
    runningOrder: 7,
  },
  {
    id: "australia",
    country: "Australia",
    flag: "🇦🇺",
    flagCode: "AU",
    artist: "Delta Goodrem",
    song: "Eclipse",
    youtubeId: "DeltaGoodremEclipse2026",
    youtubeSearch: "Delta Goodrem Eclipse Australia Eurovision 2026",
    qualified: "sf2",
    runningOrder: 8,
  },
  {
    id: "serbia",
    country: "Serbia",
    flag: "🇷🇸",
    flagCode: "RS",
    artist: "LAVINA",
    song: "Kraj Mene",
    youtubeId: "LAVINAKrajMene2026",
    youtubeSearch: "LAVINA Kraj Mene Serbia Eurovision 2026",
    qualified: "sf1",
    runningOrder: 9,
  },
  {
    id: "malta",
    country: "Malta",
    flag: "🇲🇹",
    flagCode: "MT",
    artist: "Aidan",
    song: "Bella",
    youtubeId: "AidanBella2026",
    youtubeSearch: "Aidan Bella Malta Eurovision 2026",
    qualified: "sf2",
    runningOrder: 10,
  },
  {
    id: "czechia",
    country: "Czechia",
    flag: "🇨🇿",
    flagCode: "CZ",
    artist: "Daniel Žižka",
    song: "Crossroads",
    youtubeId: "DanielZizka2026",
    youtubeSearch: "Daniel Žižka Crossroads Czechia Eurovision 2026",
    qualified: "sf2",
    runningOrder: 11,
  },
  {
    id: "bulgaria",
    country: "Bulgaria",
    flag: "🇧🇬",
    flagCode: "BG",
    artist: "Dara",
    song: "Bangaranga",
    youtubeId: "DaraBangaranga2026",
    youtubeSearch: "Dara Bangaranga Bulgaria Eurovision 2026",
    qualified: "sf2",
    runningOrder: 12,
  },
  {
    id: "croatia",
    country: "Croatia",
    flag: "🇭🇷",
    flagCode: "HR",
    artist: "LELEK",
    song: "Andromeda",
    youtubeId: "LELEKAndromeda2026",
    youtubeSearch: "LELEK Andromeda Croatia Eurovision 2026",
    qualified: "sf1",
    runningOrder: 13,
  },
  {
    id: "uk",
    country: "United Kingdom",
    flag: "🇬🇧",
    flagCode: "GB",
    artist: "LOOK MUM NO COMPUTER",
    song: "Eins, Zwei, Drei",
    youtubeId: "LookMumNoComputer2026",
    youtubeSearch: "LOOK MUM NO COMPUTER Eins Zwei Drei UK Eurovision 2026",
    qualified: "big5",
    runningOrder: 14,
  },
  {
    id: "france",
    country: "France",
    flag: "🇫🇷",
    flagCode: "FR",
    artist: "Monroe",
    song: "Regarde!",
    youtubeId: "RegardeFrance2026",
    youtubeSearch: "Monroe Regarde France Eurovision 2026",
    qualified: "big5",
    runningOrder: 15,
  },
  {
    id: "moldova",
    country: "Moldova",
    flag: "🇲🇩",
    flagCode: "MD",
    artist: "Satoshi",
    song: "Viva, Moldova!",
    youtubeId: "SatoshiVivaMoldova2026",
    youtubeSearch: "Satoshi Viva Moldova Eurovision 2026",
    qualified: "sf1",
    runningOrder: 16,
  },
  {
    id: "finland",
    country: "Finland",
    flag: "🇫🇮",
    flagCode: "FI",
    artist: "Linda Lampenius x Pete Parkkonen",
    song: "Liekinheitin",
    youtubeId: "LindaLampeniusFI2026",
    youtubeSearch: "Linda Lampenius Pete Parkkonen Liekinheitin Finland Eurovision 2026",
    qualified: "sf1",
    runningOrder: 17,
  },
  {
    id: "poland",
    country: "Poland",
    flag: "🇵🇱",
    flagCode: "PL",
    artist: "ALICJA",
    song: "Pray",
    youtubeId: "ALICJAPray2026",
    youtubeSearch: "ALICJA Pray Poland Eurovision 2026",
    qualified: "sf1",
    runningOrder: 18,
  },
  {
    id: "lithuania",
    country: "Lithuania",
    flag: "🇱🇹",
    flagCode: "LT",
    artist: "Lion Ceccah",
    song: "Sólo Quiero Más",
    youtubeId: "LionCeccah2026",
    youtubeSearch: "Lion Ceccah Sólo Quiero Más Lithuania Eurovision 2026",
    qualified: "sf1",
    runningOrder: 19,
  },
  {
    id: "sweden",
    country: "Sweden",
    flag: "🇸🇪",
    flagCode: "SE",
    artist: "FELICIA",
    song: "My System",
    youtubeId: "FELICIAMySystem2026",
    youtubeSearch: "FELICIA My System Sweden Eurovision 2026",
    qualified: "sf1",
    runningOrder: 20,
  },
  {
    id: "cyprus",
    country: "Cyprus",
    flag: "🇨🇾",
    flagCode: "CY",
    artist: "Antigoni",
    song: "Jalla",
    youtubeId: "AntigoniJalla2026",
    youtubeSearch: "Antigoni Jalla Cyprus Eurovision 2026",
    qualified: "sf2",
    runningOrder: 21,
  },
  {
    id: "italy",
    country: "Italy",
    flag: "🇮🇹",
    flagCode: "IT",
    artist: "Sal Da Vinci",
    song: "Per Sempre Sì",
    youtubeId: "SalDaVinci2026",
    youtubeSearch: "Sal Da Vinci Per Sempre Sì Italy Eurovision 2026",
    qualified: "big5",
    runningOrder: 22,
  },
  {
    id: "norway",
    country: "Norway",
    flag: "🇳🇴",
    flagCode: "NO",
    artist: "Jonas Lovv",
    song: "Ya Ya Ya",
    youtubeId: "JonasLovvYaYaYa2026",
    youtubeSearch: "Jonas Lovv Ya Ya Ya Norway Eurovision 2026",
    qualified: "sf2",
    runningOrder: 23,
  },
  {
    id: "romania",
    country: "Romania",
    flag: "🇷🇴",
    flagCode: "RO",
    artist: "Alexandra Căpitănescu",
    song: "Choke Me",
    youtubeId: "AlexandraRomania2026",
    youtubeSearch: "Alexandra Căpitănescu Choke Me Romania Eurovision 2026",
    qualified: "sf2",
    runningOrder: 24,
  },
  {
    id: "austria",
    country: "Austria",
    flag: "🇦🇹",
    flagCode: "AT",
    artist: "COSMÓ",
    song: "Tanzschein",
    youtubeId: "TanzscheinSearch", // search fallback
    youtubeSearch: "COSMÓ Tanzschein Austria Eurovision 2026",
    qualified: "host",
    runningOrder: 25,
  },
];

// Default rating categories
const DEFAULT_CATEGORIES = [
  { id: "song", label: "Song / Composition", icon: "🎵" },
  { id: "vocals", label: "Vocals", icon: "🎤" },
  { id: "staging", label: "Stage Performance", icon: "💃" },
  { id: "costume", label: "Costume & Visuals", icon: "👗" },
  { id: "overall", label: "Overall Impression", icon: "⭐" },
];
