/**
 * UK Chess Directory — Seed Data
 * Clubs include contact info; Events include duration & registration URLs
 */

function loadChessData() {
const chessClubs = [
    {
        id: 200,
        name: "Battersea Chess Club",
        lat: 51.465,
        lng: -0.165,
        address: "Battersea Labor Club, London",
        lmsId: "UK-200",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in London.",
        website: "",
        county: "London",
        events: []
    },
    {
        id: 201,
        name: "Wood Green Chess Club",
        lat: 51.595,
        lng: -0.111,
        address: "Wood Green, London",
        lmsId: "UK-201",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in London.",
        website: "",
        county: "London",
        events: []
    },
    {
        id: 202,
        name: "Hendon Chess Club",
        lat: 51.583,
        lng: -0.226,
        address: "Golders Green, London",
        lmsId: "UK-202",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in London.",
        website: "",
        county: "London",
        events: []
    },
    {
        id: 203,
        name: "Wimbledon Chess Club",
        lat: 51.421,
        lng: -0.206,
        address: "Wimbledon, London",
        lmsId: "UK-203",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in London.",
        website: "",
        county: "London",
        events: []
    },
    {
        id: 204,
        name: "Richmond & Twickenham",
        lat: 51.461,
        lng: -0.302,
        address: "Richmond, London",
        lmsId: "UK-204",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in London.",
        website: "",
        county: "London",
        events: []
    },
    {
        id: 205,
        name: "Manchester Chess Club",
        lat: 53.48,
        lng: -2.242,
        address: "Central Manchester",
        lmsId: "UK-205",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Greater Manchester.",
        website: "",
        county: "Greater Manchester",
        events: []
    },
    {
        id: 206,
        name: "3Cs Chess Club",
        lat: 53.545,
        lng: -2.113,
        address: "Oldham, Greater Manchester",
        lmsId: "UK-206",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Greater Manchester.",
        website: "",
        county: "Greater Manchester",
        events: []
    },
    {
        id: 207,
        name: "Ashton Chess Club",
        lat: 53.489,
        lng: -2.095,
        address: "Ashton-under-Lyne",
        lmsId: "UK-207",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Greater Manchester.",
        website: "",
        county: "Greater Manchester",
        events: []
    },
    {
        id: 208,
        name: "Stockport Chess Club",
        lat: 53.359,
        lng: -2.162,
        address: "Bramhall, Stockport",
        lmsId: "UK-208",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Greater Manchester.",
        website: "",
        county: "Greater Manchester",
        events: []
    },
    {
        id: 209,
        name: "Chorlton Chess Club",
        lat: 53.442,
        lng: -2.28,
        address: "Chorlton, Manchester",
        lmsId: "UK-209",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Greater Manchester.",
        website: "",
        county: "Greater Manchester",
        events: []
    },
    {
        id: 210,
        name: "Atticus Chess Club",
        lat: 53.408,
        lng: -2.991,
        address: "City Centre, Liverpool",
        lmsId: "UK-210",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Merseyside.",
        website: "",
        county: "Merseyside",
        events: []
    },
    {
        id: 211,
        name: "Aigburth Chess Club",
        lat: 53.376,
        lng: -2.936,
        address: "Aigburth, Liverpool",
        lmsId: "UK-211",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Merseyside.",
        website: "",
        county: "Merseyside",
        events: []
    },
    {
        id: 212,
        name: "Waterloo Chess Club",
        lat: 53.475,
        lng: -3.028,
        address: "Waterloo, Merseyside",
        lmsId: "UK-212",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Merseyside.",
        website: "",
        county: "Merseyside",
        events: []
    },
    {
        id: 213,
        name: "Wallasey Chess Club",
        lat: 53.424,
        lng: -3.053,
        address: "90 Manor Road, Wallasey",
        lmsId: "UK-213",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Merseyside.",
        website: "",
        county: "Merseyside",
        events: []
    },
    {
        id: 214,
        name: "Southport Chess Club",
        lat: 53.647,
        lng: -3.006,
        address: "Southport, Merseyside",
        lmsId: "UK-214",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Merseyside.",
        website: "",
        county: "Merseyside",
        events: []
    },
    {
        id: 215,
        name: "Crewe Chess Club",
        lat: 53.099,
        lng: -2.441,
        address: "St Marys Caritas, Crewe",
        lmsId: "UK-215",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cheshire.",
        website: "",
        county: "Cheshire",
        events: []
    },
    {
        id: 216,
        name: "Chester Chess Club",
        lat: 53.188,
        lng: -2.891,
        address: "The Cross Keys, Chester",
        lmsId: "UK-216",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cheshire.",
        website: "",
        county: "Cheshire",
        events: []
    },
    {
        id: 217,
        name: "Northwich Chess Club",
        lat: 53.257,
        lng: -2.518,
        address: "Gladstone Club, Northwich",
        lmsId: "UK-217",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cheshire.",
        website: "",
        county: "Cheshire",
        events: []
    },
    {
        id: 218,
        name: "Macclesfield Chess Club",
        lat: 53.258,
        lng: -2.127,
        address: "Macclesfield, Cheshire",
        lmsId: "UK-218",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cheshire.",
        website: "",
        county: "Cheshire",
        events: []
    },
    {
        id: 219,
        name: "Warrington Chess Club",
        lat: 53.389,
        lng: -2.596,
        address: "Alford Sports, Warrington",
        lmsId: "UK-219",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cheshire.",
        website: "",
        county: "Cheshire",
        events: []
    },
    {
        id: 220,
        name: "Leeds Chess Club",
        lat: 53.8,
        lng: -1.549,
        address: "Central Leeds",
        lmsId: "UK-220",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Yorkshire.",
        website: "",
        county: "West Yorkshire",
        events: []
    },
    {
        id: 221,
        name: "Bradford Chess Club",
        lat: 53.793,
        lng: -1.752,
        address: "Bradford, West Yorkshire",
        lmsId: "UK-221",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Yorkshire.",
        website: "",
        county: "West Yorkshire",
        events: []
    },
    {
        id: 222,
        name: "Halifax Chess Club",
        lat: 53.722,
        lng: -1.86,
        address: "Halifax, West Yorkshire",
        lmsId: "UK-222",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Yorkshire.",
        website: "",
        county: "West Yorkshire",
        events: []
    },
    {
        id: 223,
        name: "Huddersfield Chess Club",
        lat: 53.645,
        lng: -1.785,
        address: "Huddersfield, West Yorkshire",
        lmsId: "UK-223",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Yorkshire.",
        website: "",
        county: "West Yorkshire",
        events: []
    },
    {
        id: 224,
        name: "Wakefield Chess Club",
        lat: 53.683,
        lng: -1.498,
        address: "Wakefield, West Yorkshire",
        lmsId: "UK-224",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Yorkshire.",
        website: "",
        county: "West Yorkshire",
        events: []
    },
    {
        id: 225,
        name: "Sheffield Chess Club",
        lat: 53.381,
        lng: -1.47,
        address: "Sheffield, South Yorkshire",
        lmsId: "UK-225",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in South Yorkshire.",
        website: "",
        county: "South Yorkshire",
        events: []
    },
    {
        id: 226,
        name: "Rotherham Chess Club",
        lat: 53.43,
        lng: -1.357,
        address: "Rotherham, South Yorkshire",
        lmsId: "UK-226",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in South Yorkshire.",
        website: "",
        county: "South Yorkshire",
        events: []
    },
    {
        id: 227,
        name: "Doncaster Chess Club",
        lat: 53.522,
        lng: -1.133,
        address: "Doncaster, South Yorkshire",
        lmsId: "UK-227",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in South Yorkshire.",
        website: "",
        county: "South Yorkshire",
        events: []
    },
    {
        id: 228,
        name: "Barnsley Chess Club",
        lat: 53.552,
        lng: -1.479,
        address: "Barnsley, South Yorkshire",
        lmsId: "UK-228",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in South Yorkshire.",
        website: "",
        county: "South Yorkshire",
        events: []
    },
    {
        id: 229,
        name: "Birmingham Chess Club",
        lat: 52.486,
        lng: -1.89,
        address: "Central Birmingham",
        lmsId: "UK-229",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Midlands.",
        website: "",
        county: "West Midlands",
        events: []
    },
    {
        id: 230,
        name: "Olton Chess Club",
        lat: 52.428,
        lng: -1.811,
        address: "Solihull, West Midlands",
        lmsId: "UK-230",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Midlands.",
        website: "",
        county: "West Midlands",
        events: []
    },
    {
        id: 231,
        name: "Shirley Chess Club",
        lat: 52.413,
        lng: -1.821,
        address: "Shirley, West Midlands",
        lmsId: "UK-231",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Midlands.",
        website: "",
        county: "West Midlands",
        events: []
    },
    {
        id: 232,
        name: "Sutton Coldfield Chess Club",
        lat: 52.563,
        lng: -1.822,
        address: "Sutton Coldfield",
        lmsId: "UK-232",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Midlands.",
        website: "",
        county: "West Midlands",
        events: []
    },
    {
        id: 233,
        name: "Wolverhampton Chess Club",
        lat: 52.586,
        lng: -2.128,
        address: "Wolverhampton",
        lmsId: "UK-233",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in West Midlands.",
        website: "",
        county: "West Midlands",
        events: []
    },
    {
        id: 234,
        name: "Bristol & Clifton Chess",
        lat: 51.454,
        lng: -2.587,
        address: "Clifton, Bristol",
        lmsId: "UK-234",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Bristol.",
        website: "",
        county: "Bristol",
        events: []
    },
    {
        id: 235,
        name: "Downend & Fishponds",
        lat: 51.488,
        lng: -2.502,
        address: "Downend, Bristol",
        lmsId: "UK-235",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Bristol.",
        website: "",
        county: "Bristol",
        events: []
    },
    {
        id: 236,
        name: "South Bristol Chess Club",
        lat: 51.425,
        lng: -2.595,
        address: "South Bristol",
        lmsId: "UK-236",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Bristol.",
        website: "",
        county: "Bristol",
        events: []
    },
    {
        id: 237,
        name: "Bath Chess Club",
        lat: 51.375,
        lng: -2.359,
        address: "Bath, Somerset",
        lmsId: "UK-237",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Somerset.",
        website: "",
        county: "Somerset",
        events: []
    },
    {
        id: 238,
        name: "Frome Chess Club",
        lat: 51.23,
        lng: -2.32,
        address: "Frome, Somerset",
        lmsId: "UK-238",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Somerset.",
        website: "",
        county: "Somerset",
        events: []
    },
    {
        id: 239,
        name: "Taunton Chess Club",
        lat: 51.014,
        lng: -3.102,
        address: "Taunton, Somerset",
        lmsId: "UK-239",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Somerset.",
        website: "",
        county: "Somerset",
        events: []
    },
    {
        id: 240,
        name: "Yeovil Chess Club",
        lat: 50.941,
        lng: -2.632,
        address: "Yeovil, Somerset",
        lmsId: "UK-240",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Somerset.",
        website: "",
        county: "Somerset",
        events: []
    },
    {
        id: 241,
        name: "Exeter Chess Club",
        lat: 50.715,
        lng: -3.53,
        address: "Exeter, Devon",
        lmsId: "UK-241",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Devon.",
        website: "",
        county: "Devon",
        events: []
    },
    {
        id: 242,
        name: "Plymouth Chess Club",
        lat: 50.375,
        lng: -4.142,
        address: "Plymouth, Devon",
        lmsId: "UK-242",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Devon.",
        website: "",
        county: "Devon",
        events: []
    },
    {
        id: 243,
        name: "Newton Abbot Chess Club",
        lat: 50.53,
        lng: -3.614,
        address: "Newton Abbot, Devon",
        lmsId: "UK-243",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Devon.",
        website: "",
        county: "Devon",
        events: []
    },
    {
        id: 244,
        name: "Torquay Chess Club",
        lat: 50.461,
        lng: -3.527,
        address: "Torquay, Devon",
        lmsId: "UK-244",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Devon.",
        website: "",
        county: "Devon",
        events: []
    },
    {
        id: 245,
        name: "Bournemouth Chess Club",
        lat: 50.72,
        lng: -1.879,
        address: "Bournemouth, Dorset",
        lmsId: "UK-245",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Dorset.",
        website: "",
        county: "Dorset",
        events: []
    },
    {
        id: 246,
        name: "Poole Chess Club",
        lat: 50.715,
        lng: -1.987,
        address: "Poole, Dorset",
        lmsId: "UK-246",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Dorset.",
        website: "",
        county: "Dorset",
        events: []
    },
    {
        id: 247,
        name: "Weymouth Chess Club",
        lat: 50.609,
        lng: -2.454,
        address: "Weymouth, Dorset",
        lmsId: "UK-247",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Dorset.",
        website: "",
        county: "Dorset",
        events: []
    },
    {
        id: 248,
        name: "Southampton Chess Club",
        lat: 50.909,
        lng: -1.404,
        address: "Southampton, Hampshire",
        lmsId: "UK-248",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hampshire.",
        website: "",
        county: "Hampshire",
        events: []
    },
    {
        id: 249,
        name: "Portsmouth Chess Club",
        lat: 50.819,
        lng: -1.087,
        address: "Portsmouth, Hampshire",
        lmsId: "UK-249",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hampshire.",
        website: "",
        county: "Hampshire",
        events: []
    },
    {
        id: 250,
        name: "Winchester Chess Club",
        lat: 51.06,
        lng: -1.318,
        address: "Winchester, Hampshire",
        lmsId: "UK-250",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hampshire.",
        website: "",
        county: "Hampshire",
        events: []
    },
    {
        id: 251,
        name: "Basingstoke Chess Club",
        lat: 51.262,
        lng: -1.087,
        address: "Basingstoke, Hampshire",
        lmsId: "UK-251",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hampshire.",
        website: "",
        county: "Hampshire",
        events: []
    },
    {
        id: 252,
        name: "Brighton & Hove Chess",
        lat: 50.822,
        lng: -0.137,
        address: "Brighton, East Sussex",
        lmsId: "UK-252",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in East Sussex.",
        website: "",
        county: "East Sussex",
        events: []
    },
    {
        id: 253,
        name: "Hastings & St Leonards",
        lat: 50.854,
        lng: 0.573,
        address: "Hastings, East Sussex",
        lmsId: "UK-253",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in East Sussex.",
        website: "",
        county: "East Sussex",
        events: []
    },
    {
        id: 254,
        name: "Eastbourne Chess Club",
        lat: 50.768,
        lng: 0.284,
        address: "Eastbourne, East Sussex",
        lmsId: "UK-254",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in East Sussex.",
        website: "",
        county: "East Sussex",
        events: []
    },
    {
        id: 255,
        name: "Crowborough Chess Club",
        lat: 51.061,
        lng: 0.16,
        address: "Crowborough, East Sussex",
        lmsId: "UK-255",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in East Sussex.",
        website: "",
        county: "East Sussex",
        events: []
    },
    {
        id: 256,
        name: "Oxford City Chess Club",
        lat: 51.752,
        lng: -1.257,
        address: "Oxford, Oxfordshire",
        lmsId: "UK-256",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Oxfordshire.",
        website: "",
        county: "Oxfordshire",
        events: []
    },
    {
        id: 257,
        name: "Cowley Chess Club",
        lat: 51.733,
        lng: -1.22,
        address: "Cowley, Oxfordshire",
        lmsId: "UK-257",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Oxfordshire.",
        website: "",
        county: "Oxfordshire",
        events: []
    },
    {
        id: 258,
        name: "Banbury Chess Club",
        lat: 52.062,
        lng: -1.339,
        address: "Banbury, Oxfordshire",
        lmsId: "UK-258",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Oxfordshire.",
        website: "",
        county: "Oxfordshire",
        events: []
    },
    {
        id: 259,
        name: "Bicester Chess Club",
        lat: 51.899,
        lng: -1.153,
        address: "Bicester, Oxfordshire",
        lmsId: "UK-259",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Oxfordshire.",
        website: "",
        county: "Oxfordshire",
        events: []
    },
    {
        id: 260,
        name: "Cambridge City Chess Club",
        lat: 52.205,
        lng: 0.121,
        address: "Cambridge, Cambridgeshire",
        lmsId: "UK-260",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cambridgeshire.",
        website: "",
        county: "Cambridgeshire",
        events: []
    },
    {
        id: 261,
        name: "Peterborough Chess Club",
        lat: 52.57,
        lng: -0.247,
        address: "Peterborough",
        lmsId: "UK-261",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cambridgeshire.",
        website: "",
        county: "Cambridgeshire",
        events: []
    },
    {
        id: 262,
        name: "Ely Chess Club",
        lat: 52.399,
        lng: 0.262,
        address: "Ely, Cambridgeshire",
        lmsId: "UK-262",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cambridgeshire.",
        website: "",
        county: "Cambridgeshire",
        events: []
    },
    {
        id: 263,
        name: "St Neots Chess Club",
        lat: 52.228,
        lng: -0.266,
        address: "St Neots, Cambridgeshire",
        lmsId: "UK-263",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cambridgeshire.",
        website: "",
        county: "Cambridgeshire",
        events: []
    },
    {
        id: 264,
        name: "Norwich Chess Club",
        lat: 52.63,
        lng: 1.297,
        address: "Norwich, Norfolk",
        lmsId: "UK-264",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Norfolk.",
        website: "",
        county: "Norfolk",
        events: []
    },
    {
        id: 265,
        name: "Great Yarmouth Chess",
        lat: 52.608,
        lng: 1.73,
        address: "Great Yarmouth, Norfolk",
        lmsId: "UK-265",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Norfolk.",
        website: "",
        county: "Norfolk",
        events: []
    },
    {
        id: 266,
        name: "King's Lynn Chess Club",
        lat: 52.754,
        lng: 0.395,
        address: "King's Lynn, Norfolk",
        lmsId: "UK-266",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Norfolk.",
        website: "",
        county: "Norfolk",
        events: []
    },
    {
        id: 267,
        name: "Ipswich Chess Club",
        lat: 52.056,
        lng: 1.153,
        address: "Ipswich, Suffolk",
        lmsId: "UK-267",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Suffolk.",
        website: "",
        county: "Suffolk",
        events: []
    },
    {
        id: 268,
        name: "Bury St Edmunds Chess",
        lat: 52.247,
        lng: 0.71,
        address: "Bury St Edmunds, Suffolk",
        lmsId: "UK-268",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Suffolk.",
        website: "",
        county: "Suffolk",
        events: []
    },
    {
        id: 269,
        name: "Felixstowe Chess Club",
        lat: 51.961,
        lng: 1.351,
        address: "Felixstowe, Suffolk",
        lmsId: "UK-269",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Suffolk.",
        website: "",
        county: "Suffolk",
        events: []
    },
    {
        id: 270,
        name: "Chelmsford Chess Club",
        lat: 51.734,
        lng: 0.469,
        address: "Chelmsford, Essex",
        lmsId: "UK-270",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Essex.",
        website: "",
        county: "Essex",
        events: []
    },
    {
        id: 271,
        name: "Colchester Chess Club",
        lat: 51.889,
        lng: 0.899,
        address: "Colchester, Essex",
        lmsId: "UK-271",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Essex.",
        website: "",
        county: "Essex",
        events: []
    },
    {
        id: 272,
        name: "Southend Chess Club",
        lat: 51.545,
        lng: 0.709,
        address: "Southend-on-Sea, Essex",
        lmsId: "UK-272",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Essex.",
        website: "",
        county: "Essex",
        events: []
    },
    {
        id: 273,
        name: "Basildon Chess Club",
        lat: 51.576,
        lng: 0.448,
        address: "Basildon, Essex",
        lmsId: "UK-273",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Essex.",
        website: "",
        county: "Essex",
        events: []
    },
    {
        id: 274,
        name: "Maidstone Chess Club",
        lat: 51.278,
        lng: 0.521,
        address: "Maidstone, Kent",
        lmsId: "UK-274",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Kent.",
        website: "",
        county: "Kent",
        events: []
    },
    {
        id: 275,
        name: "Canterbury Chess Club",
        lat: 51.28,
        lng: 1.078,
        address: "Canterbury, Kent",
        lmsId: "UK-275",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Kent.",
        website: "",
        county: "Kent",
        events: []
    },
    {
        id: 276,
        name: "Tunbridge Wells Chess",
        lat: 51.132,
        lng: 0.262,
        address: "Tunbridge Wells, Kent",
        lmsId: "UK-276",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Kent.",
        website: "",
        county: "Kent",
        events: []
    },
    {
        id: 277,
        name: "Dartford Chess Club",
        lat: 51.444,
        lng: 0.22,
        address: "Dartford, Kent",
        lmsId: "UK-277",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Kent.",
        website: "",
        county: "Kent",
        events: []
    },
    {
        id: 278,
        name: "Guildford Chess Club",
        lat: 51.236,
        lng: -0.57,
        address: "Guildford, Surrey",
        lmsId: "UK-278",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Surrey.",
        website: "",
        county: "Surrey",
        events: []
    },
    {
        id: 279,
        name: "Woking Chess Club",
        lat: 51.319,
        lng: -0.558,
        address: "Woking, Surrey",
        lmsId: "UK-279",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Surrey.",
        website: "",
        county: "Surrey",
        events: []
    },
    {
        id: 280,
        name: "Epsom Chess Club",
        lat: 51.333,
        lng: -0.267,
        address: "Epsom, Surrey",
        lmsId: "UK-280",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Surrey.",
        website: "",
        county: "Surrey",
        events: []
    },
    {
        id: 281,
        name: "Farnham Chess Club",
        lat: 51.214,
        lng: -0.799,
        address: "Farnham, Surrey",
        lmsId: "UK-281",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Surrey.",
        website: "",
        county: "Surrey",
        events: []
    },
    {
        id: 282,
        name: "Reading Chess Club",
        lat: 51.454,
        lng: -0.978,
        address: "Reading, Berkshire",
        lmsId: "UK-282",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Berkshire.",
        website: "",
        county: "Berkshire",
        events: []
    },
    {
        id: 283,
        name: "Maidenhead Chess Club",
        lat: 51.522,
        lng: -0.716,
        address: "Maidenhead, Berkshire",
        lmsId: "UK-283",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Berkshire.",
        website: "",
        county: "Berkshire",
        events: []
    },
    {
        id: 284,
        name: "Slough Chess Club",
        lat: 51.51,
        lng: -0.595,
        address: "Slough, Berkshire",
        lmsId: "UK-284",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Berkshire.",
        website: "",
        county: "Berkshire",
        events: []
    },
    {
        id: 285,
        name: "Bracknell Chess Club",
        lat: 51.415,
        lng: -0.749,
        address: "Bracknell, Berkshire",
        lmsId: "UK-285",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Berkshire.",
        website: "",
        county: "Berkshire",
        events: []
    },
    {
        id: 286,
        name: "Milton Keynes Chess Club",
        lat: 52.04,
        lng: -0.759,
        address: "Milton Keynes",
        lmsId: "UK-286",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Buckinghamshire.",
        website: "",
        county: "Buckinghamshire",
        events: []
    },
    {
        id: 287,
        name: "Aylesbury Chess Club",
        lat: 51.815,
        lng: -0.812,
        address: "Aylesbury, Bucks",
        lmsId: "UK-287",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Buckinghamshire.",
        website: "",
        county: "Buckinghamshire",
        events: []
    },
    {
        id: 288,
        name: "High Wycombe Chess Club",
        lat: 51.628,
        lng: -0.748,
        address: "High Wycombe",
        lmsId: "UK-288",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Buckinghamshire.",
        website: "",
        county: "Buckinghamshire",
        events: []
    },
    {
        id: 289,
        name: "St Albans Chess Club",
        lat: 51.752,
        lng: -0.339,
        address: "St Albans, Herts",
        lmsId: "UK-289",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hertfordshire.",
        website: "",
        county: "Hertfordshire",
        events: []
    },
    {
        id: 290,
        name: "Watford Chess Club",
        lat: 51.656,
        lng: -0.39,
        address: "Watford, Herts",
        lmsId: "UK-290",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hertfordshire.",
        website: "",
        county: "Hertfordshire",
        events: []
    },
    {
        id: 291,
        name: "Stevenage Chess Club",
        lat: 51.901,
        lng: -0.202,
        address: "Stevenage, Herts",
        lmsId: "UK-291",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hertfordshire.",
        website: "",
        county: "Hertfordshire",
        events: []
    },
    {
        id: 292,
        name: "Hemel Hempstead Chess",
        lat: 51.752,
        lng: -0.469,
        address: "Hemel Hempstead, Herts",
        lmsId: "UK-292",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Hertfordshire.",
        website: "",
        county: "Hertfordshire",
        events: []
    },
    {
        id: 293,
        name: "Bedford Chess Club",
        lat: 52.135,
        lng: -0.466,
        address: "Bedford, Bedfordshire",
        lmsId: "UK-293",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Bedfordshire.",
        website: "",
        county: "Bedfordshire",
        events: []
    },
    {
        id: 294,
        name: "Luton Chess Club",
        lat: 51.878,
        lng: -0.42,
        address: "Luton, Bedfordshire",
        lmsId: "UK-294",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Bedfordshire.",
        website: "",
        county: "Bedfordshire",
        events: []
    },
    {
        id: 295,
        name: "Northampton Chess Club",
        lat: 52.24,
        lng: -0.895,
        address: "Northampton",
        lmsId: "UK-295",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Northamptonshire.",
        website: "",
        county: "Northamptonshire",
        events: []
    },
    {
        id: 296,
        name: "Kettering Chess Club",
        lat: 52.396,
        lng: -0.728,
        address: "Kettering",
        lmsId: "UK-296",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Northamptonshire.",
        website: "",
        county: "Northamptonshire",
        events: []
    },
    {
        id: 297,
        name: "Nottingham Chess Club",
        lat: 52.954,
        lng: -1.158,
        address: "Nottingham",
        lmsId: "UK-297",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Nottinghamshire.",
        website: "",
        county: "Nottinghamshire",
        events: []
    },
    {
        id: 298,
        name: "West Nottingham Chess",
        lat: 52.93,
        lng: -1.22,
        address: "Beeston, Nottingham",
        lmsId: "UK-298",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Nottinghamshire.",
        website: "",
        county: "Nottinghamshire",
        events: []
    },
    {
        id: 299,
        name: "Mansfield Chess Club",
        lat: 53.143,
        lng: -1.197,
        address: "Mansfield",
        lmsId: "UK-299",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Nottinghamshire.",
        website: "",
        county: "Nottinghamshire",
        events: []
    },
    {
        id: 300,
        name: "Derby Chess Club",
        lat: 52.922,
        lng: -1.474,
        address: "Derby, Derbyshire",
        lmsId: "UK-300",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Derbyshire.",
        website: "",
        county: "Derbyshire",
        events: []
    },
    {
        id: 301,
        name: "Chesterfield Chess Club",
        lat: 53.235,
        lng: -1.427,
        address: "Chesterfield",
        lmsId: "UK-301",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Derbyshire.",
        website: "",
        county: "Derbyshire",
        events: []
    },
    {
        id: 302,
        name: "Leicester Chess Club",
        lat: 52.636,
        lng: -1.139,
        address: "Leicester",
        lmsId: "UK-302",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Leicestershire.",
        website: "",
        county: "Leicestershire",
        events: []
    },
    {
        id: 303,
        name: "Loughborough Chess Club",
        lat: 52.77,
        lng: -1.204,
        address: "Loughborough",
        lmsId: "UK-303",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Leicestershire.",
        website: "",
        county: "Leicestershire",
        events: []
    },
    {
        id: 304,
        name: "Newcastle Chess Club",
        lat: 54.978,
        lng: -1.617,
        address: "Newcastle upon Tyne",
        lmsId: "UK-304",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Tyne and Wear.",
        website: "",
        county: "Tyne and Wear",
        events: []
    },
    {
        id: 305,
        name: "Sunderland Chess Club",
        lat: 54.906,
        lng: -1.381,
        address: "Sunderland",
        lmsId: "UK-305",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Tyne and Wear.",
        website: "",
        county: "Tyne and Wear",
        events: []
    },
    {
        id: 306,
        name: "Durham City Chess Club",
        lat: 54.775,
        lng: -1.584,
        address: "Durham",
        lmsId: "UK-306",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in County Durham.",
        website: "",
        county: "County Durham",
        events: []
    },
    {
        id: 307,
        name: "Darlington Chess Club",
        lat: 54.524,
        lng: -1.558,
        address: "Darlington",
        lmsId: "UK-307",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in County Durham.",
        website: "",
        county: "County Durham",
        events: []
    },
    {
        id: 308,
        name: "Carlisle Chess Club",
        lat: 54.892,
        lng: -2.932,
        address: "Carlisle, Cumbria",
        lmsId: "UK-308",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cumbria.",
        website: "",
        county: "Cumbria",
        events: []
    },
    {
        id: 309,
        name: "Kendal Chess Club",
        lat: 54.327,
        lng: -2.746,
        address: "Kendal, Cumbria",
        lmsId: "UK-309",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Cumbria.",
        website: "",
        county: "Cumbria",
        events: []
    },
    {
        id: 310,
        name: "Preston Chess Club",
        lat: 53.763,
        lng: -2.703,
        address: "Preston, Lancashire",
        lmsId: "UK-310",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Lancashire.",
        website: "",
        county: "Lancashire",
        events: []
    },
    {
        id: 311,
        name: "Lancaster Chess Club",
        lat: 54.047,
        lng: -2.801,
        address: "Lancaster, Lancashire",
        lmsId: "UK-311",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Lancashire.",
        website: "",
        county: "Lancashire",
        events: []
    },
    {
        id: 312,
        name: "Blackpool Chess Club",
        lat: 53.817,
        lng: -3.052,
        address: "Blackpool, Lancashire",
        lmsId: "UK-312",
        ratingType: ["ECF"],
        avgRating: 1600,
        ageGroups: ["Adult", "Senior"],
        description: "An active chess club in Lancashire.",
        website: "",
        county: "Lancashire",
        events: []
    }
];

const chessEvents = [
    {
        id: 101,
        title: "Cheshire Individual Championship 2025",
        clubId: 4, // Chester
        startDate: "2025-05-10",
        endDate: "2025-05-11",
        time: "10:00",
        type: "Championship",
        ratingType: "ECF",
        ratingMin: 0,
        ratingMax: 3000,
        ageFilter: "All",
        description: "The annual battle for the title of Cheshire Champion. Multiple sections for all levels.",
        website: "https://chesterchess.weebly.com",
        venue: "The Cross Keys, 2 Duke St, Chester CH1 1RE",
        lat: 53.1882,
        lng: -2.8918,
        entryFee: "£20",
        county: "Cheshire"
    },
    {
        id: 102,
        title: "Crewe Congress 2025",
        clubId: 1, // Crewe
        startDate: "2025-09-13",
        endDate: "2025-09-14",
        time: "09:30",
        type: "Congress",
        ratingType: "ECF",
        ratingMin: 0,
        ratingMax: 2400,
        ageFilter: "All",
        description: "A popular weekend congress with generous prize fund. Held in the heart of Crewe.",
        website: "https://crewechessclub.co.uk/congress",
        venue: "St Mary's Caritas Centre, 65 Delamere Street, Crewe, CW1 2JX",
        lat: 53.0991,
        lng: -2.4411,
        entryFee: "£30",
        county: "Cheshire"
    },
    {
        id: 103,
        title: "Stockport Rapidplay",
        clubId: 6, // Stockport
        startDate: "2025-11-23",
        endDate: "2025-11-23",
        time: "10:45",
        type: "Rapid",
        ratingType: "ECF",
        ratingMin: 0,
        ratingMax: 3000,
        ageFilter: "All",
        description: "One-day rapidplay tournament with six rounds. All welcome.",
        website: "http://www.stockportchessclub.org.uk",
        venue: "The Ladybrook, Fir Rd, Bramhall, Stockport SK7 3NY",
        lat: 53.3590,
        lng: -2.1620,
        entryFee: "£15",
        county: "Greater Manchester"
    },
    {
        id: 104,
        title: "Wirral Open 2025",
        clubId: 2, // Wallasey
        startDate: "2025-06-21",
        endDate: "2025-06-22",
        time: "10:00",
        type: "Congress",
        ratingType: "ECF",
        ratingMin: 0,
        ratingMax: 3000,
        ageFilter: "All",
        description: "A major event on the Wirral peninsula, attracting top players from the North West.",
        website: "https://merseysidechess.org.uk",
        venue: "90 Manor Road, Wallasey, Wirral CH44 1BZ",
        lat: 53.4243,
        lng: -3.0538,
        entryFee: "£25",
        county: "Merseyside"
    }
];

window.chessClubs = chessClubs;
window.chessEvents = chessEvents;
}
window.loadChessData = loadChessData;
